name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 3 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        name: Metric Left
        with:
          # Your GitHub token
          filename: metrics-left.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_notable: no
          plugin_notable_repositories: no
          plugin_habits_charts: yes
          plugin_notable_indepth: yes
          plugin_notable_from: 'all'
          plugin_isocalendar_duration: full-year
          plugin_followup: yes
          plugin_followup_sections: repositories, user
      - uses: lowlighter/metrics@latest
        name: Metrics Right
        with:
          filename: metrics-right.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_from: 750       # Use 200 events to compute habits
          plugin_habits_days: 45      # Keep only events from last 14 days
          plugin_habits_facts: yes      # Display facts section
          plugin_habits_charts: yes     # Display charts section
          plugin_habits_trim: yes       # Trim unused hours on daily chart
          config_timezone: America/Toronto # Set timezone
          plugin_activity: yes
          plugin_activity_limit: 5           # Limit to 5 events
          plugin_activity_load: 50          # Load up to 100 recent events from API (should be higher than "limit")
          plugin_activity_days: 0           # Keep only events from last 14 days (set to 0 for no limit)
          plugin_activity_filter: all        # Show all events (use table above to filter events types)
          plugin_activity_visibility: public # Only display public events
          plugin_activity_timestamps: yes    # Display events timestamps
          plugin_activity_skipped: repo      # Ignored repositories
          plugin_calendar: yes
          plugin_calendar_limit: 4
